name: Unit Testing

on:
  push:
    branches:
      - master

jobs:
  unit-test:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: 'latest'
        enable-stack: true
        stack-version: 'latest'
    - name: Run tests
      run: stack test
