name: Haskell CI

on:
  push:
    branches:
      - gh-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10.7'
        enable-stack: true
        stack-version: 'latest'
    - name: Build
      run: stack build
    - name: Run tests
      run: stack test
