name: Haskell CI

on:
  push:
    branches: [ master ]
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10.7'
        enable-stack: true
        stack-version: 'latest'

    - name: Install dependencies
      run: stack setup
    - name: Build
      run: stack build
    - name: Run tests
      run: stack test
